sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
    on:
      branch: master # source code of hexo
  local_dir: public